### ISSUE TITLE
ESLint suggestions

### ISSUE THREAD

**Issue by Jeffrey-Chang** [telusdigital/eslint-config#3]
We're trying to update from an old version to the this package. Here are some things that could help to make it possibly easier for development.

Due to ESLint being loaded in the Webpack, any errors prevents us from building the app at all. It may help with better workflow if we change some of the `error` to `warn` instead.

no-console: could be 'warn' instead of 'error'. There are times that `console.log()` is used to debug. 

Could we include one-var? It could help with bulk variable declaration. 
```
let a, b, c, d
const a = 'foo',
  b = 'bar',
  c = 'hello',
  d = 'world'
```
```
let a
let b
let c
let d
const a = 'foo'
const b = 'bar'
const c = 'hello'
const d = 'world'

**Comment by ahmadnassri** [comment]
are you relying on console log for debugging instead of ... [`debugger`](https://nodejs.org/api/debugger.html)?

make pull request for the other thing

**Comment by darcyclarke** [comment]
@Jeffrey-Chang I think @ahmadnassri made a good point about debugging best practices and I believe we chatted separately about this as well.

In terms of the bulk variable declaration, although handy, it is far more prone to error. Being verbose means being concise with it comes to variable declarations (check out these posts for other insights: http://danhough.com/blog/single-var-pattern-rant/ or http://benalman.com/news/2012/05/multiple-var-statements-javascript/).
